### ISSUE TITLE
Compatibility with gatsby-plugin-google-tagmanager

### ISSUE THREAD

**Issue by julianCast** [andrezimpel/gatsby-plugin-gdpr-cookies#102]
Hi! Good work!
Is this plugin compatible with `gatsby-plugin-google-tagmanager` ?

Because this plugin should be able to run before gatsby-plugin-google-tagmanager initializes.
This is Google official approach https://github.com/googleanalytics/ga4-tutorials/blob/0ace10747da7cfdb269f7eb484b84d49c128bbd0/tutorials/4-consent-mode/src/public/partials/consent.eta#L62C5-L62C42 based on sending the event `consent`.

**Comment by mcarturo** [comment]
Hi @julianCast,
were you able to solve this issue or figure out a workaround? apparently gatsby-plugin-google-gtag allows ga to set the cookie before having given the approval...

**Comment by julianCast** [comment]
I end up only using `gatsby-plugin-google-tagmanager`, something like:
```tsx
{
            resolve: "gatsby-plugin-google-tagmanager",
            options: {
              id: "GTM-ID",
              selfHostedOrigin: "https://domain.com",
              includeInDevelopment: false,
              // datalayer to be set before GTM is loaded
              defaultDataLayer: () => {
                let cookiesConsent = null;
                try {
                  cookiesConsent = window.localStorage.getItem("cookies_consent");
                } catch {
                  // Handle the error silently: User denied access to localStorage
                }
                return {
                  platform: "gatsby",
                  ...(cookiesConsent ? JSON.parse(cookiesConsent) : null),
                  branch: "master",
                };
              },
            },
          },
```
With proper configuration of Tag manager, no cookies will be sent before consent. Use an extension like [cookies-editor](https://chromewebstore.google.com/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm) to easily check what cookies have been set or not.

**Comment by medoms-admin** [comment]
thank you @julianCast for the response. I finally decided to do it manually without the plugin.
