### ISSUE TITLE
dataLayer doesn't update on route change

### ISSUE THREAD

**Issue by hades200082** [andrezimpel/gatsby-plugin-gdpr-cookies#12]
The dataLayer contents don't re-evaluate on route change, only on a full page reload.

To allow sending of consents through dataLayer reliably it needs to update dataLayer when the page changes.

**Comment by freesh** [comment]
Same Problem here. We use it on a onepager. So the user comes to the Landignpage, accept the cookie, but isn't tracked. He must reload the whole page to get tracked.

**Comment by theochp** [comment]
I fixed the issue by adding the following code to onAccept callback.

`onAccept={() => {
            if (typeof window !== 'undefined') { // window isn't defined during build
              window[gtmDatalayerName].push({ event: 'gatsbyRouteChange' })
            }
          }}
`
gtmDatalayer is created from an environment variable. 

Its solves the issue without having to reload the page.

**Comment by andrezimpel** [comment]
> Same Problem here. We use it on a onepager. So the user comes to the Landignpage, accept the cookie, but isn't tracked. He must reload the whole page to get tracked.
> 
> Update:
> Now my solution is to trigger a reload if the accept button in my cookie consent is clicked.
> 
> If you're using [react-cookie-consent](https://github.com/Mastermindzh/react-cookie-consent) you can set it as prop in the CookieConsent component:
> 
> ```
> <CookieConsent
>       location="bottom"
>       buttonText="I Accept"
>       cookieName="gatsby-gdpr-google-analytics"
>       onAccept={() => window.location.reload()}
> />
> ```
> 
> But it's just a quick fix and can look ugly on animated pages.

I am actually also using a reload. Currently the plugin does not know anything about a cookie banner or anything similar. It just enables tracking as soon as the cookies are set. So the UI part is really up to you. How should this work anyways? Should the initialization be not only checked on `onClientEntry` but also on every page load?

**Comment by freesh** [comment]
@andrezimpel i think you're right. It shouldn't be the task of your plugin. It's an ui problem. So i will try the solution from @theochp. :)

**Comment by alexmazza** [comment]
> Same Problem here. We use it on a onepager. So the user comes to the Landignpage, accept the cookie, but isn't tracked. He must reload the whole page to get tracked.
> 
> Update:
> Now my solution is to trigger a reload if the accept button in my cookie consent is clicked.
> 
> If you're using [react-cookie-consent](https://github.com/Mastermindzh/react-cookie-consent) you can set it as prop in the CookieConsent component:
> 
> ```
> <CookieConsent
>       location="bottom"
>       buttonText="I Accept"
>       cookieName="gatsby-gdpr-google-analytics"
>       onAccept={() => window.location.reload()}
> />
> ```
> 
> But it's just a quick fix and can look ugly on animated pages.

For google analytics I tried something like this:

`onAccept={() => {
					ReactGA.initialize('YOUR_TRACKING_ID');
					ReactGA.pageview(window.location.pathname + window.location.search);
				}}`
It works and doesn't reload the page. I'm not sure it's a good solution though.

**Comment by andrezimpel** [comment]
I'm finished up another website this week where I still have to add the whole cookie consent thing. I will have a look at the matter and how to integrate a smooth solution. :-)

**Comment by osseonews** [comment]
Have the same problem. Trying to use the solution above. But...
`I fixed the issue by adding the following code to onAccept callback.`
Where is this onAccept callback?

**Comment by andrezimpel** [comment]
> Have the same problem. Trying to use the solution above. But...
> `I fixed the issue by adding the following code to onAccept callback.`
> Where is this onAccept callback?

I guess this refers to the cookie consent plugin. Also the idea above will only initiate Google Analytics but not Facebook Pixel.

**Comment by theochp** [comment]
You can improve the idea above by using the code in https://github.com/andrezimpel/gatsby-plugin-gdpr-cookies/blob/master/src/gatsby-browser.js

Copy-paste what you need on route change

**Comment by andrezimpel** [comment]
The plugin will now check if cookies for Google Analytics or Facebook Pixel have been set between route changes on `onRouteUpdate`. Reloading the page after setting the cookies is not required anymore.
