### ISSUE TITLE
Add Google Ads

### ISSUE THREAD

**Issue by SimonKlausLudwig** [andrezimpel/gatsby-plugin-gdpr-cookies#13]
First of all, Thank you for this great plugin. I just added it to my project and wanted to add Google Ads.

Can I just add it to the tracking Ids under google analytics. We don't use google tag manager atm.

**Comment by andrezimpel** [comment]
Google Ads is currently not supported. How would the integration would look like? I'm investigating a way to add custom scripts like this.
