### ISSUE TITLE
CHROME ISSUE | Mark cross-site cookies as Secure to allow them to be sent in cross-site requests

### ISSUE THREAD

**Issue by JesoloSanDonaBasket** [andrezimpel/gatsby-plugin-gdpr-cookies#20]
![image](https://user-images.githubusercontent.com/58136642/87797405-eac2ee00-c84a-11ea-9169-e18b548b099c.png)

**Comment by andrezimpel** [comment]
Thanks! This plugin is using universal-cookie. So when setting the cookie the required things are secure: true and sameSite: none?

**Comment by andrezimpel** [comment]
@JesoloSanDonaBasket are you still having this issue? How are you setting the required cookies?

**Comment by JesoloSanDonaBasket** [comment]
Thank you @andrezimpel !! I got it solved but I didn't update it here.
