### ISSUE TITLE
GA-Autotrack

### ISSUE THREAD

**Issue by ohlr** [andrezimpel/gatsby-plugin-gdpr-cookies#23]
I tried to setup autotrack with no success.

Maybe someone of you had more luck?

https://github.com/react-ga/react-ga/issues/40
https://ga-dev-tools.appspot.com/autotrack/
https://github.com/googleanalytics/autotrack/

**Comment by andrezimpel** [comment]
Hi @ohlr, how should this be implemented? It looks like the package is also no longer maintained.

**Comment by ohlr** [comment]
It's still in thier docs: https://ga-dev-tools.appspot.com/autotrack/ but I see your point

**Comment by andrezimpel** [comment]
@ohlr I just released version 1.0.11 of the plugin. It now supports a initializeAndTrack method wich can be used in cookie banners. [See here](https://github.com/andrezimpel/gatsby-plugin-gdpr-cookies#initialize-and-track)
