### ISSUE TITLE
GTM is tracking without permission

### ISSUE THREAD

**Issue by EduSantosBrito** [andrezimpel/gatsby-plugin-gdpr-cookies#24]
This package is building tag manager in `gatsby-ssr.js`, so when I enter my website the tag manager is already working, but that's not what I want, I need that user accept cookies first, then start tag manager.

A solution is:

use `react-gtm-module` (like `react-ga`) to initialize it.

so in `onClientEntry` you can add:

```js   
    // google tagmanager
    if (
      cookies.get(options.googleTagManager.cookieName) === `true` &&
      validGTMTrackingId(options)
    ) {
      ReactGTM.initialize({ gtmId: options.googleTagManager.trackingId })
    }
```

PS: I can't do this PR now, I'm out of time :(

**Comment by freesh** [comment]
I have the same Problem.

**Comment by andrezimpel** [comment]
Thanks for looking into this @freesh! Appreciate the help a lot! This will be added to the docs by the end of the week!

**Comment by andrezimpel** [comment]
@EduSantosBrito Would you prefer the solution by @freesh?

**Comment by EduSantosBrito** [comment]
I didn't try that :D Thank you @freesh <3

**Comment by aeneasr** [comment]
I don't really understand what needs to be done to disable Google Tag Manager. I would expect that no request to `gtm.js` is made unless the `cookieName` is set properly. That's however not the case right now! The cookie is simply ignored by `gatsby-plugin-gdpr-cookies` but I would expect it to have at least some impact?
