### ISSUE TITLE
Warnings in console when using Google Analytics

### ISSUE THREAD

**Issue by trm217** [andrezimpel/gatsby-plugin-gdpr-cookies#25]
I stumbled upon an issue with this plugin which causes warnings to be printed into the console.
This issue occurs once the user has given consent and the Google Analytics consent cookie has been set with a "true" value.
![image](https://user-images.githubusercontent.com/30313631/92926170-ed515680-f43b-11ea-95e7-d44defe1ef6a.png)
While this does not seem to break anything, it still isn't very nice.
Could this be fixed?

**Comment by andrezimpel** [comment]
This will be fixed in an update by the end of the week.

**Comment by ohlr** [comment]
@trm217 is there a fix?

**Comment by trm217** [comment]
@ohlr I couldn't find one. I closed the issue since as stated above, this will be fixed in the next update.

**Comment by ohlr** [comment]
Well, usually issues are closed after the fix is in place. Please reopen

**Comment by andrezimpel** [comment]
@ohlr it has been fixed with the last version.
