### ISSUE TITLE
Send hit directly after cookie consent

### ISSUE THREAD

**Issue by fabianwohlfart** [andrezimpel/gatsby-plugin-gdpr-cookies#27]
After the user hits the accept cookies button, how would I send the initial pageview to GA?
I understand your docs the way that only the next time on `onRouteUpdate` is called it would send a pageview?
(Or if the user again loads the page and `onClientEntry` is called)

Thanks

**Comment by andrezimpel** [comment]
Thanks for using the plugin! Yes sir, currently it will only send the GA event if the window is reloaded. There will be an update this weekend where this issue will be resolved.

**Comment by fabianwohlfart** [comment]
Thank you. Looking forward!

**Comment by andrezimpel** [comment]
The plugin will now check if cookies for Google Analytics or Facebook Pixel have been set between route changes on `onRouteUpdate`. Reloading the page after setting the cookies is not required anymore. (Version 1.0.9)

**Comment by fabianwohlfart** [comment]
Okay, I know understand that you fully use `onRouteUpdate`, but still: If the cookie is set by the user I need to track the page the user is currently at. With `onRouteUpdate` only the next page will be tracked, because `onRouteUpdate` for the current page already fired, isn't it?! So is there a way to track the current page, after the cookie is set?

**Comment by fabianwohlfart** [comment]
Hey, any news on this?

**Comment by andrezimpel** [comment]
@fabianwohlfart Actually working on it rn. I'm introducing a `initializeAndTrack` method to the plugin which can be used in the frontend. I'm just trying to figure out how to get the plugin options at this point.

**Comment by tuk-solita** [comment]
This feature would be great. Keep us posted!

**Comment by oliverlambson** [comment]
Any more progress on this feature @andrezimpel? Do you have a recommendation for how to track the page hit in the meantime?

**Comment by fabianwohlfart** [comment]
As we have React Ga and Universal Cookies packages installed by this plugin we can simply use them in a method, which we call anyway, when we set the cookie to true. We used this even though we know that hardcoding our tracking id and the name of the cookie may not be the best solution. Its a temporary solution.

```
import { set, initialize, pageview } from 'react-ga'
import Cookies from 'universal-cookie'

const cookies = new Cookies()

(...)

 function initializeGA() {
    // Google Analytics
    initialize(`UA-XXX-X`)
    set('anonymizeIp', 1)
    pageview(window.location.pathname + window.location.search)

    // Gatsby Plugin
    window.GoogleAnalyticsIntialized = true
    cookies.set('gatsby-gdpr-google-analytics', 'true', { path: '/' })
  }
```

**Comment by oliverlambson** [comment]
Thanks! 

In comparing your function to the plugin I noticed that the initial pageview you are sending in that function is not the same as the pageview the plugin would send: the plugin only sends the pathname and doesn't include the search string. Not an issue for me but just thought I'd point it out in case you were expecting the plugin to include the search string and it isn't.
