### ISSUE TITLE
Analytics not initializing after consent

### ISSUE THREAD

**Issue by Joshua-Flores** [andrezimpel/gatsby-plugin-gdpr-cookies#29]
I'm using react-cookie-consent to set 'gatsby-gdpr-google-analytics' to true. However, I've noticed that once its set to true, google analytics isn't initialized and doesn't begin tracking until a page refresh or a  route change.

Any idea whats going on?

**Comment by ilyankou** [comment]
There was a lot of discussion about it (see #4 and #27), and we are waiting for @andrezimpel [to implement the feature](https://github.com/andrezimpel/gatsby-plugin-gdpr-cookies/issues/27#issuecomment-722905458)!

**Comment by andrezimpel** [comment]
It is now in version 1.0.11. [See here](https://github.com/andrezimpel/gatsby-plugin-gdpr-cookies#initialize-and-track)

**Comment by ilyankou** [comment]
Thank you so much @andrezimpel

**Comment by Joshua-Flores** [comment]
You guys rock. Just implemented it. Seems to work great.
