### ISSUE TITLE
Does not work with Google Analytics 4

### ISSUE THREAD

**Issue by FlorianMarsch** [andrezimpel/gatsby-plugin-gdpr-cookies#31]
Hi when I give consent then a analytics.js is loaded and used.

But with new GA4 its necessary to use gtag.js

**Comment by barrynorman** [comment]
Hi @andrezimpel!

I have the same issue using your plugin. 
Are you planning to upgrade your plugin? If I can help let me know.

Thanks

**Comment by ghostinside** [comment]
same, should include gtag.js instead of analytics.js

**Comment by ghostinside** [comment]
seems this lib use react-ga which does not support ga 4 yet 

https://github.com/react-ga/react-ga/issues/460

**Comment by barrynorman** [comment]
@ghostinside there is already a new package which should fix the problem: https://github.com/unrealmanu/ga-4-react

**Comment by ghostinside** [comment]
yeh, but it needs to be added to this lib

**Comment by barrynorman** [comment]
@ghostinside I can work on this. I didn't wanted to do anything before @andrezimpel replied.

**Comment by darcelvictor** [comment]
Hello, I have the issue do you know an alternative ?

**Comment by andrezimpel** [comment]
Working on this today. The new version will then also be related today, sorry for the inconvenience!

**Comment by andrezimpel** [comment]
@barrynorman feel free to open up a pull request if you already have a solution! :-)

**Comment by RaphaelPI** [comment]
Hello here :)

Any updates on this ?

**Comment by andrezimpel** [comment]
Soooo... it took quite some time to wrap my head around GA4 and how it works and how to correctly implement it so it does not send any data to Google before the user actually accepts the consent. I published v1.0.12 with GA4 support couple minutes ago.

**Comment by FlorianMarsch** [comment]
works for me, thx

**Comment by andrezimpel** [comment]
@FlorianMarsch glad to hear!
