### ISSUE TITLE
Page views recording twice with GA4

### ISSUE THREAD

**Issue by alexhillel** [andrezimpel/gatsby-plugin-gdpr-cookies#36]
I'm using version 1.0.12 with a Google Analytics 4 account, and the plugin seems to be working, except GA is recording all page views twice. This includes a first view fired by a call to `initializeAndTrack` following a cookie banner acceptance, and also through standard route changes. Only one visitor to the site is being recorded within the session, though.

My config looks like:

```
    {
      resolve: `gatsby-plugin-gdpr-cookies`,
      options: {
        googleAnalytics: {
          trackingId: 'G-6XXXXXXXXX',
          cookieName: 'siteMarketing',
          anonymize: true,
          allowAdFeatures: false,
        },
        googleTagManager: {
          trackingId: '',
          cookieName: 'siteMarketing',
          dataLayerName: 'dataLayer',
        },
        facebookPixel: {
          pixelId: '',
          cookieName: 'siteMarketing',
        },
      },
    }
```

What might be causing this issue?

**Comment by alexhillel** [comment]
Sorry, this was a logic error in the application - no actual issue!

**Comment by imadarai** [comment]
@alexhillel Can you elaborate on what logic error were you running into?  I'm having similar problem with the plugin and can't seem to figure out exactly why it's behaving that way. 
Thought instead of using or building my a custom cookie notification, I'm using [Klaro](https://heyklaro.com/) and triggering the cookie `onAccept` & `onDecline` hooks.

**Comment by alexhillel** [comment]
The plugin was registering a view on page load as I'd already accepted the banner previously - and I was also manually posting a second with the cookie banner form 'Accept' button.

**Comment by imadarai** [comment]
Thanks @alexhillel for your prompt response.  
I think my issue is originating from some other source.  Just opened an[ issue#47](https://github.com/andrezimpel/gatsby-plugin-gdpr-cookies/issues/47) to discuss it further.
