### ISSUE TITLE
support gatsby v3

### ISSUE THREAD

**Issue by gijsbotje** [andrezimpel/gatsby-plugin-gdpr-cookies#39]
hi there,

Just so it is noted, you might already be working on it, but the current version of this plugin is marked as incompatible with gatsby v3.
So supporting v3 would be great :).

**Comment by andrezimpel** [comment]
Dumb question, but how would you ensure it’s working in v2 & v3 packaging wise?

Im also working on a rewrite of the plugin (no breaking changes).

**Comment by gijsbotje** [comment]
@andrezimpel I'm far from capable of answering that question :D i use the plugin and would like to upgrade to gatsby v3. The rewrite sounds interesting and might be the time to go further with v3 and drop v2.

**Comment by andrezimpel** [comment]
@gijsbotje  Ah cool. Thanks for link. I will have a look at this and update the plugin accordingly. I will let you know when it's published to npm. (gonna have a look at this now)

**Comment by gijsbotje** [comment]
@andrezimpel Great! kudos for the fast responses!

**Comment by andrezimpel** [comment]
Just released 1.0.13 with v3 support!

**Comment by gijsbotje** [comment]
awesome! thanks @andrezimpel

**Comment by LiverpoolOwen** [comment]
> 
> 
> Just released 1.0.13 with v3 support!

Looks like there is a peer dependancy on React 16 but Gatsby v3 uses react 17 right? @andrezimpel

**Comment by andrezimpel** [comment]
Snap, you are right. Just published 1.0.14 with react 17 support. I removed react completely yesterday vor v2.
