### ISSUE TITLE
Initialize as soon as user accepts consent

### ISSUE THREAD

**Issue by romixch** [andrezimpel/gatsby-plugin-gdpr-cookies#4]
Thanks for your nice gatsby plugin! It is very convenient. But there is something that would make it even nicer:

Google Analytics is only activated when the user visits the page the second time.  Until then ReactGA reports following warning in the console:
`ReactGA.initialize must be called first or GoogleAnalytics should be loaded manually`
Should the method ReactGA.initialize somehow be incorporated into [onRouteUpdate](https://github.com/andrezimpel/gatsby-plugin-gdpr-cookies/blob/master/src/gatsby-browser.js#L44)?

**Comment by andrezimpel** [comment]
Damn. That's true. The issue with that is that currently the GA script is loaded so it's ready whenever the user accepts the consent.

I'll investiage if there's a reliable way to do this all without requiring the script within the static html of gatsby.

**Comment by andrezimpel** [comment]
Do you have a code sample on this? Also which enviroment are you using?

**Comment by andrezimpel** [comment]
@romixch I'm actually doing a reload of the page as soon as the user klicks the accept cookies button on the banner. What you could to is to initialize GA with the click on the button.

`ReactGA.initialize(options.googleAnalytics.trackingId);`

Maybe the plugin could also expose a function for this. Something like reinitialize. What do you think?

**Comment by phmasek** [comment]
@andrezimpel I implemented it the way you suggested using ReactGA. But I think it would be much more elegant if the plugin would expose the function itself as you propose. Great job with the plugin btw 👌🏻
