### ISSUE TITLE
Function to set the cookies to true

### ISSUE THREAD

**Issue by laurenskling** [andrezimpel/gatsby-plugin-gdpr-cookies#42]
This plugin does not do anything to set the cookies to `true`, correct?

Why not expose some functions to do so? There is a cookie package, we know the cookie names. Could simply export some functions to do all the work, only have to call those functions from whatever button in the site.

An idea?

**Comment by andrezimpel** [comment]
The plugin currently does not support a consent banner as well. It just handles the integration of the services. I am working on a contest banner tho which will also support setting cookies with plain javascript.

Here is a reference for that: https://plainjs.com/javascript/utilities/set-cookie-get-cookie-and-delete-cookie-5/
