### ISSUE TITLE
routeChangeEvent not fired?

### ISSUE THREAD

**Issue by bstrulak** [andrezimpel/gatsby-plugin-gdpr-cookies#44]
Hi, 
II struggle to make google tag working for my site. I am using react-cookie-consent to set gatsby-gdpr-google-tagmanager true and this is working. However, it seems like routeChangeEvent is not fired as I don't see it in google tag assistant (Tag Manager Preview Mode). I have all the triggers in GTM set correctly - with official gatsby-plugin-google-tagmanager everything is working (except of course cookie consent). 
Thank you in advance for your support.

**Comment by andrezimpel** [comment]
I gotta look into this. Which version are you using?

**Comment by bstrulak** [comment]
I'm using version 2.0.0

**Comment by andrezimpel** [comment]
Do you see any events being fired in your network tab?

**Comment by bstrulak** [comment]
How can I check this?

**Comment by andrezimpel** [comment]
There is a section for this when you inspect the website.

<img width="1093" alt="Screen Shot 2021-04-19 at 19 11 30" src="https://user-images.githubusercontent.com/1418896/115276215-0e50f700-a143-11eb-9d9a-b973d2ab227e.png">

**Comment by bstrulak** [comment]
I see there a list of resources (fonts, images, css files, js) not sure what to look for. There's also gtm.js?id=**** and ns.html?id=**** with my google tag id.

**Comment by jenkin** [comment]
Same here, `History` event is fired, but no `gatsbyRouteChange` event.

In attached screenshot you can see `dataLayer` content after first page load (all cookies are already set) and after a click on an internal link. It seems no `gatsbyRouteChange` event is pushed.

![Screenshot_20210513_182945](https://user-images.githubusercontent.com/426495/118156214-64028180-b419-11eb-8ba4-fa04ca8e9535.png)

**Comment by jenkin** [comment]
@bstrulak Please not that if you want to use Google Analytics 4 (GA4) you can bind standard page view tracking to history changes in Advanced Measurement of your Data Stream. See https://support.google.com/analytics/answer/9216061. So tracking custom `gatsbyRouteChange` event is useless, because GA4 is smart enough to track page view also in a Single Page Application such as Gatsby website.

**Comment by gabriardi** [comment]
@andrezimpel the code to initializeGoogleTagManager and trackGoogleTagManager is commented out. Is there a reason for it? Uncommenting it in makes the google tag manager work properly for me.

**Comment by andrezimpel** [comment]
@gabriardi yes. Because it was tracking events with just adding it to the DOM. Do you have 15 minutes to chat (screen share) about this?

**Comment by gabriardi** [comment]
@andrezimpel sure. I am by no means an expert at this though

**Comment by jjrchrds** [comment]
Was there any progress on this?

**Comment by fabiomaggio** [comment]
Same issue here too
@andrezimpel do you need any help on this?

**Comment by rburgst** [comment]
having the same issue here, I messed around with the code by commenting in https://github.com/andrezimpel/gatsby-plugin-gdpr-cookies/blob/master/src/services/google-tag-manager.js#L50 and I think its working then, without this it does not work. 
@andrezimpel whats the status on this, do you need a PR?

**Comment by kb1995** [comment]
I'm just trying to integrate it as well, and I also noticed that routeChangeEvent is not working. Has anyone found a solution for this?
