### ISSUE TITLE
Page Views firing twice

### ISSUE THREAD

**Issue by imadarai** [andrezimpel/gatsby-plugin-gdpr-cookies#47]
I'm using `gatsby-plugin-gdpr-cookies` with combination of `gatsby-plugin-klaro` 

I'm using klaro strictly as cookie-consent-manger and triggering functions (linked below) `onAccept` or `onReject`.  I also have event listeners on the button that trigger `initializeAndTrack(location);`
But I'm having this weird issue where google debugger is recording each route change as two page_views (see attached debugger console image), onEntry and once each page is clicked.  

I'm not sure if I'm missing some configuration on `gatsby-plugin-gdpr-cookies` or if this is an actual bug.  

![Google Analytics Debugger Image](https://i.ibb.co/C2RbRkF/Screenshot-2021-04-22-at-08-01-30-copy.png)
![gatsby-plugin-gdpr-cookies](https://i.ibb.co/vP3Xv9F/Screenshot-2021-04-22-at-08-06-21.png)
![cookie functions](https://i.ibb.co/fHgnTTm/Screenshot-2021-04-22-at-08-07-31.png)

**Comment by andrezimpel** [comment]
Hi @imadarai Thank you for using the plugin! Isn't this actually the desired behavior, to trigger a page view on entry and also when clicking the link to another page? Or are you seeing events fired although the cookies haven't been set yet?

**Comment by imadarai** [comment]
Hey @andrezimpel ! 
Thanks for your response.  I'm seeing two page_views per click (on menu).  Or every single time routeChange is triggered I see two views in Google Analytics Debugger.

**Comment by DalThePal** [comment]
I'm having a similar issue.  Upon loading the site, I am getting two page_views.  The first is a page_view on entry with page data absent, the second is a page_view with page data set as "/" as if the user had clicked on that route.  Is this intentional?

**Comment by andrezimpel** [comment]
@DalThePal no, for sure! I unfortunately can see only one event being triggered. Can you publish a codepen or allow me access to a repo to reproduce this?

/cc @imadarai

**Comment by DalThePal** [comment]
@andrezimpel unfortunately I'm not able to share the repo but I was able to figure out why it is happening.  
this snippet of code within `initializeGoogleAnalytics` is triggering a pageview because `'send_page_view': false,` is not present. https://developers.google.com/gtagjs/reference/api
```
window.gtag('config', options.trackingId, {
    'anonymize_ip': gaAnonymize,
    'allow_google_signals': gaAllowAdFeatures,
});
```

`trackGoogleAnalytics` is then being called, sending the real pageview with the correct location data.  This is resulting in two pageviews.

**Comment by andrezimpel** [comment]
@DalThePal wouldn't setting `'send_page_view': false` be an option too? 

The method `initializeGoogleAnalytics` in fact should only initialize Analytics but not send a page view. I know `trackGoogleAnalytics` is called right after that but maybe someone is using the plugin / package in a different way and is not expecting initialize to send a page view too.

**Comment by DalThePal** [comment]
@andrezimpel you're absolutely right.  I'll update my pr accordingly.
