### ISSUE TITLE
Support allowAdFeatures for Google Analytics

### ISSUE THREAD

**Issue by Odelya** [andrezimpel/gatsby-plugin-gdpr-cookies#5]
Google Analytics exposed a new property `allowAdFeatures` pls support it like in [google analytics](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/)

**Comment by andrezimpel** [comment]
I'm gonna include this asap. Or could you make a pr?

**Comment by andrezimpel** [comment]
This is now supported in v1.0.10. Could you verify that it's working as supposed?
