### ISSUE TITLE
Environments-option has no effect

### ISSUE THREAD

**Issue by DamageSami** [andrezimpel/gatsby-plugin-gdpr-cookies#53]
Hi, I am on version 2.0.0, and the environments-option in plugin config seems to have no effect.

I was running in development environment on my local machine, tested and tried out the plugin, and it seemed to work fine, so I removed the development -environment from the plugin config. But after restarting the process and a refresh, I still see that analytics and gtm is being loaded, on my browser network tab. I then also tried to remove even the production -environment from the config, but it has no effect. I have cookies with a consent present.

Is there a bug or am I missing something?

**Comment by andrezimpel** [comment]
Looking into this!

**Comment by andrezimpel** [comment]
Thank you for reporting! This was actually a bug. I'm releasing 2.0.1 right now which fixes the issue.
