### ISSUE TITLE
Issue #45 has not been merged back into v2.0

### ISSUE THREAD

**Issue by t-om** [andrezimpel/gatsby-plugin-gdpr-cookies#54]
Hi, I have just tried to install and use this plugin with npm, but I believe it must be looking at the 2.0 branch because I had the error with GA passing options.trackingId despite the object being destructured in the method, as described and fixed in #45 and #46.

In the meantime I've just installed via `npm i andrezimpel/gatsby-plugin-gdpr-cookies#master`.

Thanks!

**Comment by andrezimpel** [comment]
Yea, I'm publishing 2.0.1 in a few!
