### ISSUE TITLE
[Feature Request] Cookie names customization

### ISSUE THREAD

**Issue by jenkin** [andrezimpel/gatsby-plugin-gdpr-cookies#6]
First of all, thanks for this nice gatsby plugin! :)

I tried to use this plugin with [react-cookie-consent](https://www.npmjs.com/package/react-cookie-consent) to manage cookies, but hard-coded cookie names prevent an easy integration.

[This fork](https://github.com/Dataninja/gatsby-plugin-gdpr-cookies/tree/feature/cookie-names-customization) shows how to expose cookie names in plugin configuration. With this feature you can also set a single cookie to manage both tracking services, ie. google analytics and facebook pixel.

Of course, I can send you a PR you can review before merge.

**Comment by andrezimpel** [comment]
Thank you so much for your request! I just published v1.0.5 with custom cookie names!

**Comment by jenkin** [comment]
Please, let me know when v1.0.5 will be available on npm... :)

**Comment by andrezimpel** [comment]
Damn yea, forgot to publish it on npm. It's on there now!
