### ISSUE TITLE
Google Tag Manager firing Google Analytics fails

### ISSUE THREAD

**Issue by ergunpp** [andrezimpel/gatsby-plugin-gdpr-cookies#61]
Hi,
I have installed everything as per documents for using Google Tag Manager. I have 2 tags set up, one for facebook pixel and the other for google analytics. When I test on tag assistant, both tags get fired on "Container Loaded" but firing status for google analytics is failed whereas facebook pixel shows succeeded.
Coudn't figure out the problem.
Appreciate help.
Thanks,

**Comment by andrezimpel** [comment]
Is there maybe an issue with your Analytics implementation in Tag Manager? Do you have public url so I can see what's wrong?

**Comment by ergunpp** [comment]
Hi,
The public url is beta.prochoice.com.tr.
the same tag is working fine on prochoice.com.tr (the old site that will be replaced)
