### ISSUE TITLE
How to track outbound links

### ISSUE THREAD

**Issue by mbcod3** [andrezimpel/gatsby-plugin-gdpr-cookies#62]
I am using gatsby-plugin-google-gtag. I opted for gatsby-plugin-gdpr-cookies so that google analytics only track when user gives permission but I was tracking outbound link with

`import { OutboundLink } from "gatsby-plugin-google-gtag"`

In closed issues a year someone said this plugin uses react-ga under the hood but it doesnt seem so.

How do I do that with gatsby-plugin-gdpr-cookies?

Thanks

**Comment by andrezimpel** [comment]
dear @mbcod3 it is not anymore since it did not support GA4. You should be able to use Analytics as if you were using a non-react page.
