### ISSUE TITLE
[Feature Request] How to disable fbevents.js when not using Facebook Pixel

### ISSUE THREAD

**Issue by ajmalafif** [andrezimpel/gatsby-plugin-gdpr-cookies#7]
Getting this from lighthouse report although I am not using Facebook Pixel: https://build-065173fb-1c82-4813-b73a-28a5e25f30bc.gtsb.io/reports/lighthouse/index.html#seo

Let me know how I can help!

**Comment by andrezimpel** [comment]
Maybe we could add this to the config. So if there is no FB tracking id it also won't be initialized. What do you say, @ajmalafif?

**Comment by ajmalafif** [comment]
@andrezimpel hey yes if it's not too troubling for you that is. Make senses too given the nature of the plugin.

**Comment by andrezimpel** [comment]
Closed by #8
