### ISSUE TITLE
How to capture outbound links?

### ISSUE THREAD

**Issue by thisizkp** [andrezimpel/gatsby-plugin-gdpr-cookies#9]
Initially, I am using `gatsby-plugin-google-analytics` for the analytics setup. That library exposes a `OutboundLink` component to capture the outbound links. I think it makes sense to have something like that here too.

Thoughts?

**Comment by ColdFire87** [comment]
This plugin uses the `react-ga` npm module, which gives you access to `OutboundLink`.

```javascript
var ReactGA = require('react-ga');

render() {
  return (
    <div>
      <ReactGA.OutboundLink
        eventLabel="myLabel"
        to="http://www.example.com"
        target="_blank"
        trackerNames={['tracker2']}
      >
        My Link
      </ReactGA.OutboundLink>
    </div>
  );
}
```

See https://github.com/react-ga/react-ga#outboundlink-component

**Comment by andrezimpel** [comment]
Gonna add this to the readme. Thanks @thisizkp

**Comment by laurenskling** [comment]
> This plugin uses the `react-ga` npm module, which gives you access to `OutboundLink`.
> 
> ```js
> var ReactGA = require('react-ga');
> 
> render() {
>   return (
>     <div>
>       <ReactGA.OutboundLink
>         eventLabel="myLabel"
>         to="http://www.example.com"
>         target="_blank"
>         trackerNames={['tracker2']}
>       >
>         My Link
>       </ReactGA.OutboundLink>
>     </div>
>   );
> }
> ```
> 
> See https://github.com/react-ga/react-ga#outboundlink-component

This is no longer true?
